[package]
name = "mining_device"
version = "0.1.3"
authors = ["The Stratum V2 Developers"]
edition = "2021"
publish = false
documentation = "https://github.com/stratum-mining/stratum"
readme = "README.md"
homepage = "https://stratumprotocol.org"
repository = "https://github.com/stratum-mining/stratum"
license = "MIT OR Apache-2.0"
keywords = ["stratum", "mining", "bitcoin", "protocol"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mining_device"
path = "src/lib/mod.rs"


[dependencies]
# Using published crates from crates.io
rpc_sv2 = { version = "1.1.0" }
config_helpers_sv2 = { version = "0.1.0" }
network_helpers_sv2 = { version = "4.0.0" }
roles_logic_sv2 = { version = "5.0.0" }
# Published protocol crates to match roles_logic_sv2 v5.0.0
binary_sv2 = { version = "4.0.0" }
parsers_sv2 = { version = "0.1" }
codec_sv2 = { version = "3.0.0" }
framing_sv2 = { version = "5.0.0" }
noise_sv2 = { version = "1.1" }
common_messages_sv2 = { version = "6.0.0" }
mining_sv2 = { version = "5.0" }
buffer_sv2 = { version = "2.0" }
# Utility crates
key-utils = { version = "1.2.0" }
bitcoin = "0.32.5"
async-channel = "1.5.1"
async-recursion = "0.3.2"
rand = "0.8.4"
futures = "0.3.5"
clap = { version = "^4.5.4", features = ["derive"] }
tracing = { version = "0.1" }
tracing-subscriber = "0.3"
sha2 = { version = "0.10.6", features = ["compress", "asm"] }
tokio = "1.44.1"
primitive-types = "0.13.1"
num-format = "0.4"

[dev-dependencies]
# Criterion 0.5 without default features; combined with a dev pin of `half = 2.3.1` to stay Rust 1.75-compatible.
criterion = { version = "0.5", default-features = false, features = ["stable"] }
half = "=2.3.1"
num_cpus = "1"

[[bench]]
name = "hasher_bench"
harness = false

[[bench]]
name = "microbatch_bench"
harness = false

[[bench]]
name = "scaling_bench"
harness = false
