{
 "title": "Docker Prometheus Monitoring",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
   },
   {
    "name": "env",
    "label": "Env",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "CPU Name",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth Usage - Mining Farm Level (tcpdump)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "SV1 - Network Tx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{dst=\"10.5.0.8\", src!=\"10.5.0.16\", src!=\"192.168.65.7\", src!=\"192.168.65.254\"}[10s]))\n",
     "legendFormat": "Mining Farm Network Interface"
    }
   ]
  },
  {
   "title": "SV1 - Network Rx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{src=\"10.5.0.8\", dst!=\"10.5.0.16\", dst!=\"192.168.65.7\", dst!=\"192.168.65.254\"}[10s]))\n",
     "legendFormat": "Mining Farm Network Interface"
    }
   ]
  },
  {
   "title": "SV2 - Network Tx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{src=\"10.5.0.3\", dst!=\"192.168.65.1\", dst!=\"10.5.0.6\"}[10s]))\n",
     "legendFormat": "Template Provider"
    },
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{src=\"10.5.0.6\", dst=~\"10.5.0.4|10.5.0.5\"}[10s]))\n",
     "legendFormat": "Job Declarator Client (JDC)"
    }
   ]
  },
  {
   "title": "SV2 - Network Rx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{dst=\"10.5.0.2\", src!=\"192.168.65.1\", src!=\"10.5.0.6\"}[10s]))\n",
     "legendFormat": "Template Provider"
    },
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{dst=\"10.5.0.6\", src=~\"10.5.0.4|10.5.0.5\"}[10s]))\n",
     "legendFormat": "Job Declarator Client (JDC)"
    }
   ]
  },
  {
   "title": "Bandwidth Usage - Pool Level (tcpdump)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "SV1 - Network Tx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{src=\"10.5.0.8\", dst!=\"10.5.0.16\", dst!=\"192.168.65.7\", dst!=\"192.168.65.254\"}[10s]))\n",
     "legendFormat": "Pool"
    },
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{src=\"10.5.0.16\", dst!=\"192.168.65.1\", dst!=\"10.5.0.8\"}[10s]))",
     "legendFormat": "bitcoin-node"
    }
   ]
  },
  {
   "title": "SV1 - Network Rx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{dst=\"10.5.0.8\", src!=\"10.5.0.16\", src!=\"192.168.65.7\", src!=\"192.168.65.254\"}[10s]))\n",
     "legendFormat": "Pool"
    },
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{dst=\"10.5.0.16\", src!=\"192.168.65.1\", src!=\"10.5.0.8\"}[10s]))\n",
     "legendFormat": "bitcoin-node"
    }
   ]
  },
  {
   "title": "SV2 - Network Tx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{src=\"10.5.0.2\", dst!=\"192.168.65.1\", dst!=\"10.5.0.4\", dst!=\"10.5.0.5\"}[10s]))\n",
     "legendFormat": "Template Provider"
    },
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{src=\"10.5.0.4\", dst=\"10.5.0.6\"}[10s]))\n",
     "legendFormat": "Pool"
    },
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{src=\"10.5.0.5\", dst=\"10.5.0.6\"}[10s]))\n",
     "legendFormat": "Job Declarator Server (JDS)"
    }
   ]
  },
  {
   "title": "SV2 - Network Rx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{dst=\"10.5.0.2\", src!=\"192.168.65.1\", src!=\"10.5.0.4\", src!=\"10.5.0.5\"}[10s]))\n",
     "legendFormat": "Template Provider"
    },
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{dst=\"10.5.0.4\", src=\"10.5.0.6\"}[10s]))\n",
     "legendFormat": "Pool"
    },
    {
     "expr": "sum by (id, name) (irate(ntm_bytes_total{dst=\"10.5.0.5\", src=\"10.5.0.6\"}[10s]))\n",
     "legendFormat": "Job Declarator Server (JDS)"
    }
   ]
  },
  {
   "title": "SV1 roles performances (cAvisor)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Pool Roles - CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"sv1-public-pool\"}[1m])) by (id, name) \n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"sv1-public-pool\"}\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles - Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_transmit_bytes_total{name=~\"sv1-public-pool\"}[5m]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles - Network Rx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_receive_bytes_total{name=~\"sv1-public-pool\"}[5m]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "SV2 roles performances (cAdvisor)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pool Roles - CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"sv2-tp-pool-side|sv2-pool|sv2-jds\"}[1m])) by (id, name) \n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles - Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"sv2-tp-pool-side|sv2-pool|sv2-jds\"}\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles - Network Tx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_transmit_bytes_total{name=~\"sv2-tp-pool-side|sv2-pool|sv2-jds\"}[10s]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pool Roles - Network Rx ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_receive_bytes_total{name=~\"sv2-tp-pool-side|sv2-pool|sv2-jds\"}[10s]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Miner Roles - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"sv2-tp-miner-side|sv2-jdc|sv2-translator\"}[1m])) by (id, name) \n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Miner Roles - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"sv2-tp-miner-side|sv2-jdc|sv2-translator\"}\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Miner Roles - Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_transmit_bytes_total{name=~\"sv2-tp-miner-side|sv2-jdc|sv2-translator\"}[10s]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Miner Roles - Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (id, name) (irate(container_network_receive_bytes_total{name=~\"sv2-tp-miner-side|sv2-jdc|sv2-translator\"}[10s]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Host Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Targets Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( node_filesystem_avail_bytes {mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"}) ",
     "legendFormat": "Free Storage"
    }
   ]
  }
 ]
}