name: Auto Rebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITGAB_SRI_PERSONAL_TOKEN }}
          fetch-depth: 0  # Fetch completo per avere tutta la cronologia

      - name: Set GH_TOKEN environment variable
        run: echo "GH_TOKEN=${{ secrets.GITGAB_SRI_PERSONAL_TOKEN }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITGAB_SRI_PERSONAL_TOKEN }}

      - name: Fetch open pull requests
        run: |
          gh auth setup-git
          gh pr list --state open --json number,headRepositoryOwner,headRefName --jq '.[] | "\(.number) \(.headRepositoryOwner.login) \(.headRefName)"' > pr_details.txt
        env:
          GH_TOKEN: ${{ secrets.GITGAB_SRI_PERSONAL_TOKEN }}

      - name: Rebase pull requests
        run: |
          while read pr_number pr_owner pr_branch; do
            echo "Processing PR #$pr_number"

            # Add the contributor's fork as a remote
            git remote add contributor https://github.com/$pr_owner/$(gh repo view --json name -q '.name').git

            # Fetch the contributor's branches
            git fetch contributor

            # Checkout the branch from the contributor's fork
            git checkout -b contributor-branch contributor/$pr_branch

            # Set the committer name and email to match the PR author
            PR_AUTHOR_NAME=$(gh pr view $pr_number --json author --jq '.author.login')
            PR_AUTHOR_EMAIL="${PR_AUTHOR_NAME}@users.noreply.github.com"

            git config user.name "$PR_AUTHOR_NAME"
            git config user.email "$PR_AUTHOR_EMAIL"

            # Rebase the branch on top of the main branch
            git fetch origin main
            git rebase origin/main || {
              echo "Conflict detected. Aborting rebase and continuing."
              git rebase --abort
              continue
            }

            # Push the rebased branch back to the contributor's fork
            git push --force-with-lease contributor contributor-branch:$pr_branch

            # Remove the remote
            git remote remove contributor
          done < pr_details.txt
        env:
          GH_TOKEN: ${{ secrets.GITGAB_SRI_PERSONAL_TOKEN }}
