name: Auto Rebase

on:
  push:
    branches:
      - main  # Triggera la action quando c'è un push sul branch `main`
  workflow_dispatch:  # Permette di eseguire manualmente la action dal tab Actions su GitHub

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set GH_TOKEN environment variable
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch open pull requests
        run: |
          gh auth setup-git
          gh pr list --state open --json number --jq '.[].number' > pr_numbers.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase pull requests
        run: |
          while read pr; do
            echo "Rebasing PR #$pr"
            gh pr checkout $pr
            git fetch origin main
            git rebase origin/main
            git push --force-with-lease
          done < pr_numbers.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
