on:
  push:
    branches:
      - main
    # Run when pull requests get labeled
  pull_request:
      types: [labeled]

jobs:
  auto-rebase:
      name: AutoRebase
      runs-on: ubuntu-latest
      steps:
        - name: Get Token
          id: create_token
          uses: tibdex/github-app-token@v2
          with:
            app_id: ${{ secrets.APP_ID }}
            private_key: ${{ secrets.APP_PRIVATE_KEY }}
            
        - name: autorebase    
          uses: Label305/AutoRebase@v0.1
          with:
            github_token: ${{ steps.create_token.outputs.token }}
