name: Auto Rebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's default token
          fetch-depth: 0  # Fetch full history to have the entire commit history

      - name: Fetch open pull requests with label
        run: |
          gh auth setup-git
          gh pr list --state open --label "ready-to-be-merged" --json number,headRepositoryOwner,headRefName --jq '.[] | "\(.number) \(.headRepositoryOwner.login) \(.headRefName)"' > pr_details.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's default token

      - name: Rebase pull requests
        run: |
          while read pr_number pr_owner pr_branch; do
            echo "Processing PR #$pr_number"

            # Add the contributor's fork as a remote
            git remote add contributor https://github.com/$pr_owner/$(gh repo view --json name -q '.name').git

            # Fetch the contributor's branches
            git fetch contributor

            # Checkout the branch from the contributor's fork
            git checkout -b contributor-branch contributor/$pr_branch

            # Set the committer name and email to match the PR author
            PR_AUTHOR_NAME=$(gh pr view $pr_number --json author --jq '.author.login')
            PR_AUTHOR_EMAIL="${PR_AUTHOR_NAME}@users.noreply.github.com"

            git config user.name "$PR_AUTHOR_NAME"
            git config user.email "$PR_AUTHOR_EMAIL"

            # Rebase the branch on top of the main branch
            git fetch origin main
            git rebase origin/main || {
              echo "Conflict detected. Aborting rebase and continuing."
              git rebase --abort
              continue
            }

            # Push the rebased branch back to the contributor's fork
            git push --force-with-lease contributor contributor-branch:$pr_branch

            # Remove the remote
            git remote remove contributor

            # Restart the check suite for the pull request
            PR_HEAD_SHA=$(gh pr view $pr_number --json headRefOid --jq '.headRefOid')
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/check-suites/$PR_HEAD_SHA/rerequest
          done < pr_details.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITGAB_SRI_PERSONAL_TOKEN }}  # Use GitHub's default token
