name: Semver Check

on:
  pull_request:
    branches:
      - "main"

jobs:
  semver-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install cargo-semver-checks
        run: cargo install cargo-semver-checks --version 0.37.0 --locked

      - name: Run semver checks for utils/buffer
        working-directory: utils/buffer
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/binary-sv2/codec
        working-directory: protocols/v2/binary-sv2/codec
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/binary-sv2
        working-directory: protocols/v2/binary-sv2
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/framing-sv2
        working-directory: protocols/v2/framing-sv2
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/noise-sv2
        working-directory: protocols/v2/noise-sv2
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/codec-sv2
        working-directory: protocols/v2/codec-sv2
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/subprotocols/common-messages
        working-directory: protocols/v2/subprotocols/common-messages
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/subprotocols/job-declaration
        working-directory: protocols/v2/subprotocols/job-declaration
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/subprotocols/mining
        working-directory: protocols/v2/subprotocols/mining
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/subprotocols/template-distribution
        working-directory: protocols/v2/subprotocols/template-distribution
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/roles-logic-sv2
        working-directory: protocols/v2/roles-logic-sv2
        run: cargo semver-checks --default-features

      - name: Run semver checks for protocols/v2/channels-sv2
        working-directory: protocols/v2/channels-sv2
        run: cargo semver-checks

      - name: Run semver checks for protocols/v2/parsers-sv2
        working-directory: protocols/v2/parsers-sv2
        run: cargo semver-checks
      
      - name: Run semver checks for protocols/v2/handlers-sv2
        working-directory: protocols/v2/handlers-sv2
        run: cargo semver-checks

      - name: Run semver checks for protocols/v1
        working-directory: protocols/v1
        run: cargo semver-checks

      - name: Run semver checks for utils/bip32-key-derivation
        working-directory: utils/bip32-key-derivation
        run: cargo semver-checks

      - name: Run semver checks for protocols/stratum-translation
        working-directory: protocols/stratum-translation
        run: cargo semver-checks

      # TODO: Uncomment this when the stratum-core crate is published to crates.io
      # - name: Run semver checks for stratum-core
      #  working-directory: stratum-core
      #  run: cargo semver-checks

      # TODO: Uncomment this when the stratum-apps crate is published to crates.io
      # - name: Run semver checks for roles/stratum-apps
      #  working-directory: roles/stratum-apps
      #  run: cargo semver-checks
